version: "3.9"
services:
  solefi:
    image: registry.iguzman.com.mx/solefi:${BRANCH}
    restart: unless-stopped
    # environment:
    #   - REACT_APP_API_URL=${REACT_APP_API_URL}
    #   - REACT_APP_BRANCH_NAME=${REACT_APP_BRANCH_NAME}
    #   - REACT_APP_FACEBOOK_APP_ID=${REACT_APP_FACEBOOK_APP_ID}
    #   - REACT_APP_PRODUCTION=${REACT_APP_PRODUCTION}
    volumes:
      - /apps/solefi/static:/static
      - /apps/solefi/assets:/assets
    ports:
      - "${PUBLIC_PORT}:3000"
